//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.1, generator: @autorest/go@4.0.0-preview.43)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package saasapi

// FulfillmentOperationsClientActivateSubscriptionResponse contains the response from method FulfillmentOperationsClient.ActivateSubscription.
type FulfillmentOperationsClientActivateSubscriptionResponse struct {
	// placeholder for future response values
}

// FulfillmentOperationsClientDeleteSubscriptionResponse contains the response from method FulfillmentOperationsClient.DeleteSubscription.
type FulfillmentOperationsClientDeleteSubscriptionResponse struct {
	// OperationLocationURI contains the information returned from the Operation-Location header response.
	OperationLocationURI *string
}

// FulfillmentOperationsClientGetSubscriptionResponse contains the response from method FulfillmentOperationsClient.GetSubscription.
type FulfillmentOperationsClientGetSubscriptionResponse struct {
	Subscription
}

// FulfillmentOperationsClientListAvailablePlansResponse contains the response from method FulfillmentOperationsClient.ListAvailablePlans.
type FulfillmentOperationsClientListAvailablePlansResponse struct {
	SubscriptionPlans
}

// FulfillmentOperationsClientListSubscriptionsResponse contains the response from method FulfillmentOperationsClient.ListSubscriptions.
type FulfillmentOperationsClientListSubscriptionsResponse struct {
	SubscriptionsResponse
}

// FulfillmentOperationsClientResolveResponse contains the response from method FulfillmentOperationsClient.Resolve.
type FulfillmentOperationsClientResolveResponse struct {
	ResolvedSubscription
}

// FulfillmentOperationsClientUpdateSubscriptionResponse contains the response from method FulfillmentOperationsClient.UpdateSubscription.
type FulfillmentOperationsClientUpdateSubscriptionResponse struct {
	// OperationLocationURI contains the information returned from the Operation-Location header response.
	OperationLocationURI *string
}

// SubscriptionOperationsClientGetOperationStatusResponse contains the response from method SubscriptionOperationsClient.GetOperationStatus.
type SubscriptionOperationsClientGetOperationStatusResponse struct {
	Operation
}

// SubscriptionOperationsClientListOperationsResponse contains the response from method SubscriptionOperationsClient.ListOperations.
type SubscriptionOperationsClientListOperationsResponse struct {
	OperationList
}

// SubscriptionOperationsClientUpdateOperationStatusResponse contains the response from method SubscriptionOperationsClient.UpdateOperationStatus.
type SubscriptionOperationsClientUpdateOperationStatusResponse struct {
	// placeholder for future response values
}

